name: Update

on:
  schedule:
    - cron: '0 16 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare for results
      run: |
        git clone --depth=1 --branch=results --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" results
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Nintendo eShop
      continue-on-error: true
      run: |
        python Nintendo_eShop.py
    - name: Microsoft Store (Xbox)
      continue-on-error: true
      run: |
        python Microsoft_Store.py
    - name: Save results
      run: |
        pushd results/ &>/dev/null
        rm *.json
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit -m "From GitHub Actions build ${GITHUB_RUN_NUMBER}"
        git push
        popd &>/dev/null
